
language: node_js
node_js: "10.16.0"

addons:
  postgresql: "9.6"

cache:
  directories:
    - "node_modules"
    - $HOME/.npm

install:
  - npm ci

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: us-east-2
    app: retina
    env: develop
    bucket_name: elasticbeanstalk-us-east-2-814839865406
    on:
      repo: Renascentinc/retina-api
      branch: develop

  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: us-east-2
    app: retina
    env: production
    bucket_name: elasticbeanstalk-us-east-2-814839865406
    on:
      repo: Renascentinc/retina-api
      branch: master
      condition: $TRAVIS_BRANCH = master
